// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

maps/alienshooter_demo.bsp
maps/alienshooter_demo.cfg
maps/alienshooter_demo.gmr
maps/alienshooter_demo.gsr
maps/alienshooter_demo.res
maps/alienshooter_demo_motd.txt
models/alienshooter/alien/alien_green.mdl
models/alienshooter/alien/alien_red.mdl
models/alienshooter/alien/alien_yellow.mdl
models/alienshooter/alien_grenade_cross.mdl
models/alienshooter/alien_health_cross.mdl
models/alienshooter/alien_health_huge.mdl
models/alienshooter/alien_minigun_cross.mdl
models/alienshooter/alien_rpgammo_cross.mdl
models/alienshooter/alien_shot_cross.mdl
models/alienshooter/alien_vest_cross.mdl
models/alienshooter/alien_vest_red.mdl
models/alienshooter/alien_vest_yell.mdl
models/alienshooter/fork.mdl
models/alienshooter/grass_3.mdl
models/alienshooter/nope.mdl
models/alienshooter/p_alien_mini.mdl
models/alienshooter/p_alien_nade.mdl
models/alienshooter/p_alien_pistol.mdl
models/alienshooter/p_alien_rpg.mdl
models/alienshooter/w_alien_mini.mdl
models/alienshooter/w_alien_nade.mdl
models/alienshooter/w_alien_rpg.mdl
models/alienshooter/w_alien_shot.mdl
scripts/maps/alien/alien_map_effect.as
scripts/maps/alien/alien_map_int.as
scripts/maps/alien/alien_player_hook.as
scripts/maps/alien/alien_weapons.as
scripts/maps/alien/item_alien.as
scripts/maps/alien/point_checkpoint.as
scripts/maps/alien/weapon_alien_mini.as
scripts/maps/alien/weapon_alien_nade.as
scripts/maps/alien/weapon_alien_pistol.as
scripts/maps/alien/weapon_alien_rpg.as
scripts/maps/alien/weapon_alien_shotgun.as
sound/alienshooter/ammo_pickup.wav
sound/alienshooter/big_explosion.wav
sound/alienshooter/bomb_activate.wav
sound/alienshooter/drop_item.wav
sound/alienshooter/drop_shell.wav
sound/alienshooter/drop_shell2.wav
sound/alienshooter/energy_off.wav
sound/alienshooter/energy_on.wav
sound/alienshooter/footsteps.wav
sound/alienshooter/generator.wav
sound/alienshooter/granade_luncher.wav
sound/alienshooter/machine_gun.wav
sound/alienshooter/menu_mus_01.mp3
sound/alienshooter/monster1_attack.wav
sound/alienshooter/monster_death.wav
sound/alienshooter/monster_death2.wav
sound/alienshooter/monster_hit.wav
sound/alienshooter/monster_hit2.wav
sound/alienshooter/mus00_01.mp3
sound/alienshooter/mus01_01.mp3
sound/alienshooter/mus02_01.mp3
sound/alienshooter/pick_armor.wav
sound/alienshooter/pistol_shot.wav
sound/alienshooter/rocket_launch.wav
sound/alienshooter/shotgun.wav
sound/alienshooter/take_healh.wav
sound/alienshooter/weapon_pickup.wav
sprites/alien/weapon_alien_mini.txt
sprites/alien/weapon_alien_nade.txt
sprites/alien/weapon_alien_pistol.txt
sprites/alien/weapon_alien_rpg.txt
sprites/alien/weapon_alien_shotgun.txt
