// Created with resguy v6 (November 2017)
// https://github.com/wootguy/resguy

gfx/env/asciiart2bk.tga
gfx/env/asciiart2dn.tga
gfx/env/asciiart2ft.tga
gfx/env/asciiart2lf.tga
gfx/env/asciiart2rt.tga
gfx/env/asciiart2up.tga
models/player/aan/aan.bmp
models/player/aan/aan.mdl
models/player/uboa/uboa.bmp
models/player/uboa/uboa.mdl
models/player/uboa2/uboa2.bmp
models/player/uboa2/uboa2.mdl
models/player/uboa2b/uboa2b.bmp
models/player/uboa2b/uboa2b.mdl
models/player/uboab/uboab.bmp
models/player/uboab/uboab.mdl
models/uboa/babygarg.mdl
models/uboa/babygargt.mdl
models/uboa/dokupe.mdl
models/uboa/hdhakase.mdl
models/uboa/ichybarney.mdl
models/uboa/ichybarneyT.mdl
models/uboa/ichyhakase.mdl
models/uboa/kanateko.mdl
models/uboa/kimohakase.mdl
models/uboa/konichiwa.mdl
models/uboa/moripo.mdl
models/uboa/overmk2.mdl
models/uboa/slahakase.mdl
models/uboa/uboablack.mdl
models/uboa/uboawhite.mdl
models/uboa/uboazombie.mdl
models/uboa/uboazombie01.mdl
models/uboa/uboazombie02.mdl
models/uboa/uboazombie03.mdl
models/uboa/uboazombieT.mdl
models/uboa/whitehakase.mdl
models/uboa/wrench.mdl
sound/uboa/ac.wav
sound/uboa/gj.wav
sound/uboa/ichybarney/ichy_alert1.wav
sound/uboa/ichybarney/ichy_alert2.wav
sound/uboa/ichybarney/ichy_alert3.wav
sound/uboa/ichybarney/ichy_attack1.wav
sound/uboa/ichybarney/ichy_attack2.wav
sound/uboa/ichybarney/ichy_bite1.wav
sound/uboa/ichybarney/ichy_bite2.wav
sound/uboa/ichybarney/ichy_die1.wav
sound/uboa/ichybarney/ichy_die2.wav
sound/uboa/ichybarney/ichy_die3.wav
sound/uboa/ichybarney/ichy_die4.wav
sound/uboa/ichybarney/ichy_idle1.wav
sound/uboa/ichybarney/ichy_idle2.wav
sound/uboa/ichybarney/ichy_idle3.wav
sound/uboa/ichybarney/ichy_idle4.wav
sound/uboa/ichybarney/ichy_pain1.wav
sound/uboa/ichybarney/ichy_pain2.wav
sound/uboa/ichybarney/ichy_pain3.wav
sound/uboa/ichybarney/ichy_pain4.wav
sound/uboa/ichybarney/ichy_pain5.wav
sound/uboa/ichyhakase/ichy_alert1.wav
sound/uboa/ichyhakase/ichy_alert2.wav
sound/uboa/ichyhakase/ichy_alert3.wav
sound/uboa/ichyhakase/ichy_attack1.wav
sound/uboa/ichyhakase/ichy_attack2.wav
sound/uboa/ichyhakase/ichy_bite1.wav
sound/uboa/ichyhakase/ichy_bite2.wav
sound/uboa/ichyhakase/ichy_die1.wav
sound/uboa/ichyhakase/ichy_die2.wav
sound/uboa/ichyhakase/ichy_die3.wav
sound/uboa/ichyhakase/ichy_die4.wav
sound/uboa/ichyhakase/ichy_idle1.wav
sound/uboa/ichyhakase/ichy_idle2.wav
sound/uboa/ichyhakase/ichy_idle3.wav
sound/uboa/ichyhakase/ichy_idle4.wav
sound/uboa/ichyhakase/ichy_pain1.wav
sound/uboa/ichyhakase/ichy_pain2.wav
sound/uboa/ichyhakase/ichy_pain3.wav
sound/uboa/ichyhakase/ichy_pain4.wav
sound/uboa/ichyhakase/ichy_pain5.wav
sound/uboa/jackal.wav
sound/uboa/konichiwa/attack.wav
sound/uboa/konichiwa/konichiwa.wav
sound/uboa/konichiwa/konichiwa2.wav
sound/uboa/konichiwa/konichiwa3.wav
sound/uboa/konichiwa/miss.wav
sound/uboa/moripo/ara.wav
sound/uboa/moripo/ara2.wav
sound/uboa/moripo/ara3.wav
sound/uboa/uboazombie/zo_pain1.wav
sound/uboa/uboazombie/zo_pain2.wav
sound/uboa/zkare.wav
