// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/clcampaign/p_hgun.mdl
models/clcampaign/v_hgun.mdl
models/clcampaign/v_shotgun.mdl
models/clcampaign/w_hgun.mdl
models/cracklife/agrunt.mdl
models/cracklife/barney.mdl
models/cracklife/big_mom.mdl
models/cracklife/bullsquid.mdl
models/cracklife/controller.mdl
models/cracklife/garg.mdl
models/cracklife/gman.mdl
models/cracklife/headcrab.mdl
models/cracklife/hgrunt.mdl
models/cracklife/hornet.mdl
models/cracklife/houndeye.mdl
models/cracklife/icky.mdl
models/cracklife/islave.mdl
models/cracklife/nihilanth.mdl
models/cracklife/null.mdl
models/cracklife/p_9mmhandgun.mdl
models/cracklife/p_egon.mdl
models/cracklife/p_gauss.mdl
models/cracklife/p_grenade.mdl
models/cracklife/p_hgun.mdl
models/cracklife/p_satchel.mdl
models/cracklife/p_shotgun.mdl
models/cracklife/p_squeak.mdl
models/cracklife/rpgrocket.mdl
models/cracklife/scientist.mdl
models/cracklife/tree.mdl
models/cracklife/turret.mdl
models/cracklife/v_357.mdl
models/cracklife/v_9mmar.mdl
models/cracklife/v_9mmhandgun.mdl
models/cracklife/v_crowbar.mdl
models/cracklife/v_egon_v2.mdl
models/cracklife/v_gauss_v2.mdl
models/cracklife/v_grenade.mdl
models/cracklife/v_hgun.mdl
models/cracklife/v_rpg.mdl
models/cracklife/v_satchel.mdl
models/cracklife/v_shotgun.mdl
models/cracklife/v_squeak.mdl
models/cracklife/w_9mmhandgun.mdl
models/cracklife/w_crowbar.mdl
models/cracklife/w_egon.mdl
models/cracklife/w_gauss.mdl
models/cracklife/w_grenade.mdl
models/cracklife/w_hgun.mdl
models/cracklife/w_rpgammo.mdl
models/cracklife/w_satchel.mdl
models/cracklife/w_shotgun.mdl
models/cracklife/w_squeak.mdl
models/cracklife/zombie.mdl
sound/clcampaign/weapons/dbarrel1.wav
sound/clcampaign/weapons/sbarrel1.wav
sound/clcampaign/weapons/scock1.wav
sound/cracklife/agrunt/ag_alert1.wav
sound/cracklife/agrunt/ag_alert2.wav
sound/cracklife/agrunt/ag_alert3.wav
sound/cracklife/agrunt/ag_fire1.wav
sound/cracklife/ambience/_comma.wav
sound/cracklife/ambience/aliencave1.wav
sound/cracklife/ambience/alienflyby1.wav
sound/cracklife/ambience/alienvalve2.wav
sound/cracklife/ambience/biggun1.wav
sound/cracklife/ambience/computalk1.wav
sound/cracklife/ambience/jetflyby1.wav
sound/cracklife/ambience/mgun_burst1.wav
sound/cracklife/ambience/pulsemachine.wav
sound/cracklife/ambience/rifle1.wav
sound/cracklife/ambience/waterfall1.wav
sound/cracklife/ambience/wind1.wav
sound/cracklife/apache/ap_rotor1.wav
sound/cracklife/aslave/slv_alert1.wav
sound/cracklife/aslave/slv_alert4.wav
sound/cracklife/aslave/slv_word1.wav
sound/cracklife/aslave/slv_word2.wav
sound/cracklife/aslave/slv_word3.wav
sound/cracklife/aslave/slv_word4.wav
sound/cracklife/aslave/slv_word5.wav
sound/cracklife/aslave/slv_word6.wav
sound/cracklife/aslave/slv_word7.wav
sound/cracklife/aslave/slv_word8.wav
sound/cracklife/barney/ba_dontmake.wav
sound/cracklife/barney/ba_dotoyou.wav
sound/cracklife/barney/ba_duty.wav
sound/cracklife/barney/ba_endline.wav
sound/cracklife/barney/ba_friends.wav
sound/cracklife/barney/ba_iwish.wav
sound/cracklife/barney/ba_later.wav
sound/cracklife/barney/ba_pain1.wav
sound/cracklife/barney/ba_pain3.wav
sound/cracklife/barney/ba_post.wav
sound/cracklife/barney/ba_raincheck.wav
sound/cracklife/barney/ba_somuch.wav
sound/cracklife/barney/ba_stepoff.wav
sound/cracklife/barney/ba_tomb.wav
sound/cracklife/barney/ba_whoathere.wav
sound/cracklife/barney/c1a0_ba_late.wav
sound/cracklife/barney/fuckyou.wav
sound/cracklife/bullchicken/bc_attackgrowl.wav
sound/cracklife/bullchicken/bc_idle1.wav
sound/cracklife/bullchicken/bc_idle3.wav
sound/cracklife/buttons/blip1.wav
sound/cracklife/buttons/button1.wav
sound/cracklife/buttons/button10.wav
sound/cracklife/buttons/button2.wav
sound/cracklife/buttons/button3.wav
sound/cracklife/buttons/button4.wav
sound/cracklife/buttons/button5.wav
sound/cracklife/buttons/button6.wav
sound/cracklife/buttons/button7.wav
sound/cracklife/buttons/button8.wav
sound/cracklife/buttons/button9.wav
sound/cracklife/buttons/latchlocked1.wav
sound/cracklife/buttons/latchunlocked1.wav
sound/cracklife/buttons/latchunlocked2.wav
sound/cracklife/common/bodydrop3.wav
sound/cracklife/common/bodysplat.wav
sound/cracklife/common/npc_step1.wav
sound/cracklife/common/npc_step2.wav
sound/cracklife/debris/beamstart1.wav
sound/cracklife/debris/beamstart3.wav
sound/cracklife/debris/bustceiling.wav
sound/cracklife/debris/bustconcrete1.wav
sound/cracklife/debris/bustconcrete2.wav
sound/cracklife/debris/bustcrate1.wav
sound/cracklife/debris/bustflesh2.wav
sound/cracklife/debris/bustglass1.wav
sound/cracklife/debris/metal4.wav
sound/cracklife/debris/zap1.wav
sound/cracklife/debris/zap2.wav
sound/cracklife/debris/zap3.wav
sound/cracklife/debris/zap4.wav
sound/cracklife/debris/zap5.wav
sound/cracklife/debris/zap6.wav
sound/cracklife/debris/zap7.wav
sound/cracklife/debris/zap8.wav
sound/cracklife/doors/doormove1.wav
sound/cracklife/doors/doormove2.wav
sound/cracklife/doors/doormove3.wav
sound/cracklife/doors/doormove5.wav
sound/cracklife/doors/doormove6.wav
sound/cracklife/doors/doorstop1.wav
sound/cracklife/doors/doorstop2.wav
sound/cracklife/doors/doorstop3.wav
sound/cracklife/doors/doorstop5.wav
sound/cracklife/doors/doorstop8.wav
sound/cracklife/garg/gar_attack1.wav
sound/cracklife/gman/gman_mumble2.wav
sound/cracklife/gman/gman_mumble3.wav
sound/cracklife/gman/gman_mumble6.wav
sound/cracklife/hgrunt/_comma.wav
sound/cracklife/hgrunt/alien1.wav
sound/cracklife/hgrunt/alien2.wav
sound/cracklife/hgrunt/alien3.wav
sound/cracklife/hgrunt/charge1.wav
sound/cracklife/hgrunt/charge2.wav
sound/cracklife/hgrunt/charge3.wav
sound/cracklife/hgrunt/charge4.wav
sound/cracklife/hgrunt/clik.wav
sound/cracklife/hgrunt/cover1.wav
sound/cracklife/hgrunt/cover2.wav
sound/cracklife/hgrunt/cover3.wav
sound/cracklife/hgrunt/freeman1.wav
sound/cracklife/hgrunt/freeman2.wav
sound/cracklife/hgrunt/freeman3.wav
sound/cracklife/hgrunt/gr_die1.wav
sound/cracklife/hgrunt/gr_die2.wav
sound/cracklife/hgrunt/gr_die3.wav
sound/cracklife/hgrunt/gr_pain1.wav
sound/cracklife/hgrunt/gr_pain2.wav
sound/cracklife/hgrunt/gr_pain4.wav
sound/cracklife/hgrunt/gr_pain5.wav
sound/cracklife/hgrunt/gr_reload1.wav
sound/cracklife/hgrunt/grenade1.wav
sound/cracklife/hgrunt/grenade2.wav
sound/cracklife/hgrunt/grenade3.wav
sound/cracklife/hgrunt/taunt1.wav
sound/cracklife/hgrunt/taunt2.wav
sound/cracklife/hgrunt/taunt3.wav
sound/cracklife/hgrunt/taunt4.wav
sound/cracklife/hgrunt/taunt5.wav
sound/cracklife/hgrunt/taunt6.wav
sound/cracklife/hgrunt/throw1.wav
sound/cracklife/hgrunt/throw2.wav
sound/cracklife/hgrunt/throw3.wav
sound/cracklife/items/medcharge4.wav
sound/cracklife/items/suitcharge1.wav
sound/cracklife/items/suitchargeno1.wav
sound/cracklife/plats/bigstop1.wav
sound/cracklife/plats/elevbell1.wav
sound/cracklife/plats/elevmove2.wav
sound/cracklife/plats/train_use1.wav
sound/cracklife/player/pl_metal1.wav
sound/cracklife/player/pl_metal2.wav
sound/cracklife/player/pl_metal4.wav
sound/cracklife/player/pl_swim1.wav
sound/cracklife/player/pl_swim2.wav
sound/cracklife/player/pl_swim3.wav
sound/cracklife/player/pl_swim4.wav
sound/cracklife/scientist/c1a0_sci_catscream.wav
sound/cracklife/scientist/c1a0_sci_dis17a.wav
sound/cracklife/scientist/c1a0_sci_dis4a.wav
sound/cracklife/scientist/c1a0_sci_stayback.wav
sound/cracklife/scientist/c1a2_sci_dangling.wav
sound/cracklife/scientist/c1a4_sci_rocket.wav
sound/cracklife/scientist/c1a4_sci_tent.wav
sound/cracklife/scientist/c2a5_sci_lebuz.wav
sound/cracklife/scientist/c3a2_sci_1glu.wav
sound/cracklife/scientist/c3a2_sci_3glu.wav
sound/cracklife/scientist/fail.wav
sound/cracklife/scientist/follow1.wav
sound/cracklife/scientist/follow2.wav
sound/cracklife/scientist/follow3.wav
sound/cracklife/scientist/follow4.wav
sound/cracklife/scientist/sci_aftertest.wav
sound/cracklife/scientist/sci_alone.wav
sound/cracklife/squeek/sqk_deploy1.wav
sound/cracklife/taunts/taunt1.wav
sound/cracklife/taunts/taunt2.wav
sound/cracklife/taunts/taunt3.wav
sound/cracklife/taunts/taunt4.wav
sound/cracklife/tride/c0a0_tr_arrive.wav
sound/cracklife/tride/c0a0_tr_dest.wav
sound/cracklife/tride/c0a0_tr_emerg.wav
sound/cracklife/tride/c0a0_tr_exit.wav
sound/cracklife/tride/c0a0_tr_gmorn.wav
sound/cracklife/tride/c0a0_tr_haz.wav
sound/cracklife/tride/c0a0_tr_jobs.wav
sound/cracklife/tride/c0a0_tr_noeat.wav
sound/cracklife/tride/c0a0_tr_time.wav
sound/cracklife/tride/c0a0_tr_tourn.wav
sound/cracklife/weapons/357_cock1.wav
sound/cracklife/weapons/357_shot1.wav
sound/cracklife/weapons/cbar_hit1.wav
sound/cracklife/weapons/cbar_hit2.wav
sound/cracklife/weapons/dbarrel1.wav
sound/cracklife/weapons/egon_off1.wav
sound/cracklife/weapons/egon_run3.wav
sound/cracklife/weapons/egon_windup2.wav
sound/cracklife/weapons/explode3.wav
sound/cracklife/weapons/explode4.wav
sound/cracklife/weapons/explode5.wav
sound/cracklife/weapons/gauss2.wav
sound/cracklife/weapons/mortar.wav
sound/cracklife/weapons/mortarhit.wav
sound/cracklife/weapons/reload1.wav
sound/cracklife/weapons/sbarrel1.wav
sound/cracklife/weapons/scock1.wav
sound/cracklife/weapons/xbow_hit1.wav
sound/cracklife/weapons/xbow_hit2.wav
sound/cracklife/x/x_attack1.wav
sound/cracklife/x/x_attack2.wav
sound/cracklife/x/x_attack3.wav
sound/cracklife/x/x_die1.wav
sound/cracklife/x/x_pain1.wav
sound/cracklife/x/x_pain3.wav
sound/cracklife/x/x_recharge1.wav
sound/cracklife/x/x_recharge2.wav
sound/cracklife/x/x_teleattack1.wav
sprites/cracklife/640hud1.spr
sprites/cracklife/640hud2.spr
sprites/cracklife/640hud4.spr
sprites/cracklife/640hud5.spr
sprites/cracklife/640hud7.spr
sprites/cracklife/logo.spr
sprites/cracklife/weapon_clcrowbar.txt
sprites/cracklife/weapon_clgauss.txt
sprites/cracklife/weapon_clglock.txt
sprites/cracklife/weapon_clhornetgun.txt
sprites/cracklife/weapon_clmp5.txt
sprites/cracklife/weapon_clpython.txt
sprites/cracklife/weapon_clshotgun.txt
