gfx/env/sky_l1escape7_bk.tga
gfx/env/sky_l1escape7_dn.tga
gfx/env/sky_l1escape7_ft.tga
gfx/env/sky_l1escape7_lf.tga
gfx/env/sky_l1escape7_rt.tga
gfx/env/sky_l1escape7_up.tga
maps/cs_blitzwar.bsp
models/csripent/bgman.mdl
models/csripent/knifer.mdl
models/csripent/knifer01.mdl
models/csripent/p_9mmar.mdl
models/csripent/p_9mmhandgun.mdl
models/csripent/p_crowbar.mdl
models/csripent/p_desert_eagle.mdl
models/csripent/p_grenade.mdl
models/csripent/p_m16.mdl
models/csripent/p_m40a1.mdl
models/csripent/p_saw.mdl
models/csripent/p_shotgun.mdl
models/csripent/p_uzi.mdl
models/csripent/p_uzi_gold.mdl
models/csripent/speed.mdl
models/csripent/speed01.mdl
models/csripent/v_9mmar.mdl
models/csripent/v_9mmhandgun.mdl
models/csripent/v_crowbar.mdl
models/csripent/v_desert_eagle.mdl
models/csripent/v_grenade.mdl
models/csripent/v_m16a2.mdl
models/csripent/v_m40a1.mdl
models/csripent/v_medkit.mdl
models/csripent/v_saw.mdl
models/csripent/v_shotgun.mdl
models/csripent/v_uzi.mdl
models/csripent/weaponmodels.txt
models/csripent/w_9mmar.mdl
models/csripent/w_9mmhandgun.mdl
models/csripent/w_crowbar.mdl
models/csripent/w_crowbart.mdl
models/csripent/w_desert_eagle.mdl
models/csripent/w_grenade.mdl
models/csripent/w_m16.mdl
models/csripent/w_m40a1.mdl
models/csripent/w_saw.mdl
models/csripent/w_shotgun.mdl
models/csripent/w_uzi.mdl
models/cs_blitzwar/apc_arctic.mdl
models/cs_blitzwar/bushb.mdl
models/cs_blitzwar/tree3.mdl
models/cs_blitzwar/tree5.mdl
models/cs_blitzwar/tree_greyv1.mdl
models/cs_blitzwar/ZILGAVNOVAZIL.mdl
sound/ambience/buzzer_shumgoroda.wav
sound/csripent/scare.wav
sound/csripent/woo.wav
sound/csripent/knifer/attack.wav
sound/csripent/knifer/miss.wav
sound/cs_blitzwar/knifer.txt
sound/weapons/CS/ak47_boltpull.wav
sound/weapons/CS/ak47_clipin.wav
sound/weapons/CS/ak47_clipout.wav
sound/weapons/CS/awp_clipin.wav
sound/weapons/CS/awp_clipout.wav
sound/weapons/CS/boltdown.wav
sound/weapons/CS/boltpull1.wav
sound/weapons/CS/boltup.wav
sound/weapons/CS/clipin1.wav
sound/weapons/CS/clipout1.wav
sound/weapons/CS/cliprelease1.wav
sound/weapons/CS/de_clipin.wav
sound/weapons/CS/de_clipout.wav
sound/weapons/CS/de_deploy.wav
sound/weapons/CS/famas_boltpull.wav
sound/weapons/CS/famas_boltslap.wav
sound/weapons/CS/famas_clipin.wav
sound/weapons/CS/famas_clipout.wav
sound/weapons/CS/famas_forearm.wav
sound/weapons/CS/fireinthehole.wav
sound/weapons/CS/knife_draw.wav
sound/weapons/CS/m249_boxin.wav
sound/weapons/CS/m249_boxout.wav
sound/weapons/CS/m249_chain.wav
sound/weapons/CS/m249_coverdown.wav
sound/weapons/CS/m249_coverup.wav
sound/weapons/CS/mac10_boltpull.wav
sound/weapons/CS/mac10_clipin.wav
sound/weapons/CS/mac10_clipout.wav
sound/weapons/CS/mac10_draw.wav
sound/weapons/CS/slideback1.wav
sound/weapons/CS/sliderelease1.wav
sprites/csripent/kmgr.spr
