// Created with resguy v6 (November 2017)
// https://github.com/wootguy/resguy

holiday.wad
models/afrikakorps/misc/palm1A.mdl
models/afrikakorps/misc/palm1B.mdl
models/afrikakorps/misc/palm2.mdl
models/holiday/barn.mdl
models/holiday/barn01.mdl
models/holiday/barn02.mdl
models/holiday/barn03.mdl
models/holiday/barnT.mdl
models/holiday/civ_paper_scientist.mdl
models/holiday/civ_scientist.mdl
sound/holiday/acdc.wav
sound/holiday/beach.wav
sound/holiday/dkong.wav
sound/holiday/grolsch.wav
sound/holiday/jackals.wav
sound/holiday/pacman.wav
sound/holiday/primal.wav
sound/holiday/rammstein.wav
sound/party/beat116m.wav
sound/party/beat16m.wav
sound/party/beat216m.wav
sound/party/beat316m.wav
sound/party/beat416m.wav
sound/party/beat516m.wav
sound/party/beat616m.wav
sound/party/deepack16m.wav
sound/party/melo116m.wav
sound/party/melo216m.wav
sound/party/melo316m.wav
sound/party/melo416m.wav
sound/party/melo516m.wav
sound/party/melo616m.wav
sound/party/nrgintro.wav
sound/party/nrgmid.wav
sound/party/scratch.wav
sound/party/sound116m.wav
sound/party/sound216m.wav
sound/party/sound316m.wav
sound/party/sound416m.wav
sound/party/sound516m.wav
sound/party/sound616m.wav
