// Created with resguy v8 (September 2018)
// https://github.com/wootguy/resguy

hqsplit1.wad
hqsplit2.wad
hqsplit4.wad
models/hquakerip/barney.mdl
models/hquakerip/barney01.mdl
models/hquakerip/barney02.mdl
models/hquakerip/barney03.mdl
models/hquakerip/barneyT.mdl
models/hquakerip/headcrab.mdl
models/hquakerip/headcrabT.mdl
models/hquakerip/hgrunt.mdl
models/hquakerip/hgrunt01.mdl
models/hquakerip/hgrunt02.mdl
models/hquakerip/hgrunt03.mdl
models/hquakerip/hgruntT.mdl
models/hquakerip/islave.mdl
models/hquakerip/islave01.mdl
models/hquakerip/islave02.mdl
models/hquakerip/islaveT.mdl
models/hquakerip/miniturret.mdl
models/hquakerip/miniturretT.mdl
models/hquakerip/p_crowbar.mdl
models/hquakerip/scientist.mdl
models/hquakerip/scientist01.mdl
models/hquakerip/scientist02.mdl
models/hquakerip/scientist03.mdl
models/hquakerip/scientist04.mdl
models/hquakerip/scientist05.mdl
models/hquakerip/scientist06.mdl
models/hquakerip/scientist07.mdl
models/hquakerip/scientistT.mdl
models/hquakerip/turret.mdl
models/hquakerip/turretT.mdl
models/hquakerip/v_crowbar.mdl
models/hquakerip/w_crowbar.mdl
models/hquakerip/w_crowbart.mdl
sound/hq2/pest_1.WAV
sound/hq2/pest_5.WAV
sound/hq2/pest_ost1.WAV
sound/hq2/pest_ost10.WAV
sound/hq2/pest_ost11.WAV
sound/hq2/pest_ost12.WAV
sound/hq2/pest_ost13.WAV
sound/hq2/pest_ost14.WAV
sound/hq2/pest_ost15.WAV
sound/hq2/pest_ost16.WAV
sound/hq2/pest_ost2.WAV
sound/hq2/pest_ost3.WAV
sound/hq2/pest_ost4.WAV
sound/hq2/pest_ost5.WAV
sound/hq2/pest_ost6.WAV
sound/hq2/pest_ost7.WAV
sound/hq2/pest_ost8.WAV
sound/hq2/pest_ost9.WAV
sound/hq2/quiz_no.WAV
sound/hq2/quiz_no2.WAV
sound/hq2/quiz_yes.WAV
sound/hq2/quiz_yes2.WAV
sound/patience/quiz_bg.WAV
sound/pestilence/bg.wav
sprites/Royal-soldier_MapDesigns.spr
models/player/royal-soldier/royal-soldier.mdl
