// Created with resguy v8 (September 2018)
// https://github.com/wootguy/resguy

hqsplit1.wad
hqsplit2.wad
hqsplit3.wad
hqsplit5.wad
models/hquakerip/barney.mdl
models/hquakerip/barney01.mdl
models/hquakerip/barney02.mdl
models/hquakerip/barney03.mdl
models/hquakerip/barneyT.mdl
models/hquakerip/headcrab.mdl
models/hquakerip/headcrabT.mdl
models/hquakerip/hgrunt.mdl
models/hquakerip/hgrunt01.mdl
models/hquakerip/hgrunt02.mdl
models/hquakerip/hgrunt03.mdl
models/hquakerip/hgruntT.mdl
models/hquakerip/islave.mdl
models/hquakerip/islave01.mdl
models/hquakerip/islave02.mdl
models/hquakerip/islaveT.mdl
models/hquakerip/miniturret.mdl
models/hquakerip/miniturretT.mdl
models/hquakerip/p_crowbar.mdl
models/hquakerip/scientist.mdl
models/hquakerip/scientist01.mdl
models/hquakerip/scientist02.mdl
models/hquakerip/scientist03.mdl
models/hquakerip/scientist04.mdl
models/hquakerip/scientist05.mdl
models/hquakerip/scientist06.mdl
models/hquakerip/scientist07.mdl
models/hquakerip/scientistT.mdl
models/hquakerip/turret.mdl
models/hquakerip/turretT.mdl
models/hquakerip/v_crowbar.mdl
models/hquakerip/w_crowbar.mdl
models/hquakerip/w_crowbart.mdl
sound/ambience/sil2.WAV
sound/ambience/sil_base.wav
sound/ambience/sil_break2.WAV
sound/ambience/sil_drums.wav
sound/ambience/sil_piano.wav
sound/ambience/sil_piano2.wav
sound/ambience/sil_string.wav
sound/pestilence/bg.wav
models/player/royal-soldier/royal-soldier.mdl
