halflife.wad
xeno.wad
gfx/env/xeno8up.tga
gfx/env/xeno8dn.tga
gfx/env/xeno8lf.tga
gfx/env/xeno8rt.tga
gfx/env/xeno8ft.tga
gfx/env/xeno8bk.tga
models/afrikakorps/misc/palm1a.mdl
models/hunger/hungerzombie.mdl
sound/keen/spartaaloop.mp3
sound/keen/spartaaa.wav
sound/keen/potatochip.wav
sound/keen/ohsnap.wav
sprites/exit1.spr
models/turr/betty.mdl
sprites/poison.spr
sprites/d-tele1.spr
sprites/tele1.spr
sound/ambience/alien_builder.wav
sound/ambience/alien_beacon.wav
sound/misc/secret.wav
sprites/xspark1.spr
sound/ambience/crtnoise.wav
