maps/kyper_kuutio_1.res
maps/kyper_kuutio_2.res
maps/kyper_kuutio_3.res
maps/kyper_kuutio_1.cfg
maps/kyper_kuutio_2.cfg
maps/kyper_kuutio_3.cfg
maps/kyper_kuutio_1_skl.cfg
maps/kyper_kuutio_2_skl.cfg
maps/kyper_kuutio_3_skl.cfg
maps/kyper_kuutio_1_motd.txt
maps/kyper_kuutio_2_motd.txt
maps/kyper_kuutio_3_motd.txt
gfx/env/hydramantibk.tga
gfx/env/hydramantidn.tga
gfx/env/hydramantift.tga
gfx/env/hydramantilf.tga
gfx/env/hydramantirt.tga
gfx/env/hydramantiup.tga
models/rngstuff/kyper_kuutio/kyper_assistant.mdl
models/rngstuff/kyper_kuutio/mr_zombie3.mdl
models/rngstuff/kyper_kuutio/ld_barnabus.mdl
models/rngstuff/kyper_kuutio/ae_pipesystem.mdl
models/rngstuff/kyper_kuutio/ae_pumper.mdl
models/rngweapons/kyper_kuutio/pee/p_kyperbow.mdl
models/rngweapons/kyper_kuutio/v_kyperbow.mdl
models/rngweapons/kyper_kuutio/wee/w_kyperbow.mdl
models/rngweapons/kyper_kuutio/pee/p_exoshotgun.mdl
models/rngweapons/kyper_kuutio/pee/p_microgun.mdl
models/rngweapons/kyper_kuutio/v_exoshotgun.mdl
models/rngweapons/kyper_kuutio/v_microgun.mdl
models/rngweapons/kyper_kuutio/wee/w_exoshotgun.mdl
models/rngweapons/kyper_kuutio/wee/w_microgun.mdl
models/rngweapons/kyper_kuutio/pee/p_gausspistol.mdl
models/rngweapons/kyper_kuutio/v_gausspistol.mdl
models/rngweapons/kyper_kuutio/wee/w_gausspistol.mdl
models/rngweapons/kyper_kuutio/pee/p_electrogun.mdl
models/rngweapons/kyper_kuutio/v_electrogun.mdl
models/rngweapons/kyper_kuutio/wee/w_electrogun.mdl
models/rngweapons/kyper_kuutio/pee/p_omegacannon.mdl
models/rngweapons/kyper_kuutio/v_omegacannon.mdl
models/rngweapons/kyper_kuutio/wee/w_omegacannon.mdl
models/rngweapons/kyper_kuutio/pee/p_mininuke.mdl
models/rngweapons/kyper_kuutio/pee/p_mininuke_r.mdl
models/rngweapons/kyper_kuutio/v_mininuke.mdl
models/rngweapons/kyper_kuutio/wee/w_mininuke.mdl
models/rngweapons/kyper_kuutio/wee/w_mininuke_ammo.mdl
models/rngweapons/kyper_kuutio/wee/mininuke_rocket.mdl
models/rngweapons/p_rngmace.mdl
models/rngweapons/v_rngmace.mdl
models/rngweapons/w_rngmace.mdl
sound/rng/kyper_kuutio/kyper_kuutio_intro.ogg
sound/rng/kyper_kuutio/kyper_kuutio_introb.ogg
sound/rng/kyper_kuutio/kyper_kuutio_intro2.ogg
sound/rng/kyper_kuutio/kyper_kuutio_outro.ogg
sound/rng/kyper_kuutio/kyper_kuutio_loop.ogg
sound/rng/kyper_kuutio/kyper_kuutio2_loop.ogg
sound/rng/kyper_kuutio/kyper_kuutio3_loop.ogg
sound/rng/kyper_kuutio/kyper_kuutio3b_loop.ogg
sound/rng/kyper_kuutio/kyper_kuutio4_loop.ogg
sound/rng/kyper_kuutio/kyper_kuutio_ship.wav
sound/rng/kyper_kuutio/kyper_kuutio_ship2.wav
sound/rng/kyper_kuutio/kyper_kuutio_trigger.wav
sound/rng/kyper_kuutio/kyper_kuutio_trigger2.wav