maps/sc_avp.cfg
maps/sc_avp.txt
maps/sc_avp_motd.txt
maps/sc_avp2.cfg
maps/sc_avp2_motd.txt
maps/sc_avp3.cfg
maps/sc_avp3_motd.txt
maps/sc_avp4.cfg
maps/sc_avp4_motd.txt
maps/sc_avp5.cfg
maps/sc_avp5_motd.txt
maps/sc_avp6.cfg
maps/sc_avp6_motd.txt
maps/sc_avp7.cfg
maps/sc_avp7_motd.txt
maps/sc_avp8.cfg
maps/sc_avp8_motd.txt
maps/sc_avp9.cfg
maps/sc_avp9_motd.txt

gfx/env/spacebk.bmp
gfx/env/spacebk.tga
gfx/env/spacedn.bmp
gfx/env/spacedn.tga
gfx/env/spaceft.bmp
gfx/env/spaceft.tga
gfx/env/spacelf.bmp
gfx/env/spacelf.tga
gfx/env/spacert.bmp
gfx/env/spacert.tga
gfx/env/spaceup.bmp
gfx/env/spaceup.tga

models/amckern/bigbluetruck.mdl
models/amckern/dr_feal_good.mdl
models/amckern/garg33.mdl
models/amckern/garg33T.mdl
models/amckern/hgrunt.mdl
models/amckern/hgruntT.mdl
models/amckern/max_scientist.mdl
models/amckern/mini_zombie_barney.mdl
models/amckern/mini_zombie_soldier.mdl
models/amckern/null.mdl
models/amckern/Ourano.mdl
models/amckern/ouranogibs.mdl
models/amckern/p_toad.mdl
models/amckern/plant_pod2.mdl
models/amckern/readme.txt
models/amckern/robobug2.mdl
models/amckern/rubbish.mdl
models/amckern/Tree2.mdl
models/amckern/tree4.mdl
models/amckern/v_shotgun.mdl
models/amckern/v_toad.mdl
models/amckern/v_xenhands.mdl
models/amckern/w_toad.mdl
models/amckern/woodgibs.mdl

models/max/bigbluetruck.mdl
models/max/hgrunt.mdl
models/max/hgruntT.mdl
models/max/null.mdl
models/max/p_357.mdl
models/max/readme.txt
models/max/rubbish.mdl
models/max/scientist.mdl
models/max/v_357.mdl
models/max/w_357.mdl
models/max/woodgibs.mdl

sound/amckern/b6.wav
sound/amckern/break_wood_box_01.wav
sound/amckern/car1.wav
sound/amckern/distantbattle.wav
sound/amckern/Door_slide.wav
sound/amckern/intro.wav
sound/amckern/klaxon2.wav
sound/amckern/lift_hum_loop.wav
sound/amckern/locked_in1.wav
sound/amckern/lockedin_bang.wav
sound/amckern/lv_neon.wav
sound/amckern/police_alert_01.wav
sound/amckern/readme.txt
sound/amckern/regroup.wav
sound/amckern/sc_avp8.wav
sound/amckern/sc_avp8_ambince.wav
sound/amckern/sc_avp8_radio2.wav
sound/amckern/sc_avp8_radio.wav
sound/amckern/sc_avp9_train_idle1.wav
sound/amckern/sc_avp9_train_idle2.wav
sound/amckern/sc_avp9_train_idle.wav
sound/amckern/security_access_denied.wav
sound/amckern/security_access_granted.wav
sound/amckern/sub_hiss.wav
sound/amckern/target_found.wav
sound/amckern/thunder1.wav
sound/amckern/truck.wav
sound/amckern/tv_add1.wav
sound/amckern/tv_add2.wav
sound/amckern/tv_add3.wav
sound/amckern/tv_add4.wav
sound/amckern/tv_add5.wav
sound/amckern/tv_add6.wav
sound/amckern/tv_add7.wav
sound/amckern/tv_add8.wav
sound/amckern/tv_add_end.wav
sound/amckern/what_body.wav

sprites/amckern/air_con_drip.spr