\\map by 巫术蛊师(Dr.Abc)
sc_tkou.wad
models\sc_tkou\helicopter_blackhawk-new.mdl
models\sc_tkou\leclerc.mdl
models\sc_tkou\car_bombed.mdl
models\sc_tkou\palm1A.mdl
models\sc_tkou\palm2.mdl
models\sc_tkou\rustcar3.mdl
models\sc_tkou\truck_large-brown.mdl
models\sc_tkou\w_kevlar.mdl
models\sc_tkou\w_medkit.mdl
models\sc_tkou\papapa\p_knife.mdl
models\sc_tkou\papapa\p_m1911.mdl
models\sc_tkou\papapa\v_9mmar.mdl
models\sc_tkou\papapa\v_grenade.mdl
models\sc_tkou\papapa\v_knife.mdl
models\sc_tkou\papapa\v_m16a2.mdl
models\sc_tkou\papapa\v_m1911.mdl
models\sc_tkou\papapa\v_shotgun.mdl
models\sc_tkou\papapa\v_uzi.mdl
models\sc_tkou\papapa\w_knife.mdl
models\sc_tkou\papapa\w_m1911.mdl
models\sc_tkou\wawawa\hkou.mdl
models\sc_tkou\wawawa\kou.mdl
models\sc_tkou\wawawa\kout.mdl
models\sc_tkou\wawawa\VIP.mdl
sound\sc_tkou\ambient_guns2.wav
sound\sc_tkou\arabmusic.wav
sound\sc_tkou\blackhawk_idle_loop.wav
sound\sc_tkou\hr_failure.wav
sound\sc_tkou\t_gotanint_ru.wav
maps\sc_tkou.bsp
maps\sc_tkou.cfg
maps\sc_tkou.txt
maps\sc_tkou.res
