gfx/env/sc_tropicalbk.tga
gfx/env/sc_tropicaldn.tga
gfx/env/sc_tropicalft.tga
gfx/env/sc_tropicallf.tga
gfx/env/sc_tropicalrt.tga
gfx/env/sc_tropicalup.tga
maps/sc_tropical_final_motd.txt
maps/sc_tropical1_final_motd.txt
maps/sc_tropical2_final_motd.txt
maps/sc_tropical3_final_motd.txt
maps/sc_tropical_final.cfg
maps/sc_tropical1_final.cfg
maps/sc_tropical2_final.cfg
maps/sc_tropical3_final.cfg
maps/sc_tropical_final.res
maps/sc_tropical1_final.res
maps/sc_tropical2_final.res
maps/sc_tropical3_final.res
models/sc_tropical/pred_plant.mdl
models/sc_tropical/tree2.mdl
models/sc_tropical/pi_fern.mdl
models/sc_tropical/chair_office.mdl
models/sc_tropical/chaise.mdl
models/sc_tropical/coffee_maker.mdl
models/sc_tropical/coffee_props-cup.mdl
models/sc_tropical/couch_leather-black.mdl
models/sc_tropical/fire_extinguisher.mdl
models/sc_tropical/p_9mmar.mdl
models/sc_tropical/p_9mmhandgun.mdl
models/sc_tropical/p_crowbar.mdl
models/sc_tropical/p_rpg.mdl
models/sc_tropical/w_9mmar.mdl
models/sc_tropical/w_9mmhandgun.mdl
models/sc_tropical/w_crowbar.mdl
models/sc_tropical/w_rpg.mdl
models/sc_tropical/v_9mmar.mdl
models/sc_tropical/v_9mmhandgun.mdl
models/sc_tropical/v_crowbar.mdl
models/sc_tropical/v_rpg.mdl
models/sc_tropical/v_m40a1.mdl
sound/sc_tropical/ark_waterfall.wav
sound/sc_tropical/ark_waterfall2.wav
sound/sc_tropical/waterrun.wav
sound/sc_tropical/lost_intro.wav
sound/sc_tropical/lost_end.wav
sound/sc_tropical/lost_success.wav
sprites/sc_tropical/cs_ark_waterfall.spr
sprites/sc_tropical/watersmoke.spr