maps/sc_waterflow.bsp
maps/sc_waterflow.cfg
maps/sc_waterflow.res
maps/sc_waterflow_motd.txt
sprites/null.spr
sprites/waterflow/watermist.spr
gfx/env/DalePeninsula_README.txt
gfx/env/DalePeninsula_256_bk.bmp
gfx/env/DalePeninsula_256_bk.jpg
gfx/env/DalePeninsula_256_bk.pcx
gfx/env/DalePeninsula_256_bk.tga
gfx/env/DalePeninsula_256_dn.bmp
gfx/env/DalePeninsula_256_dn.jpg
gfx/env/DalePeninsula_256_dn.pcx
gfx/env/DalePeninsula_256_dn.tga
gfx/env/DalePeninsula_256_ft.bmp
gfx/env/DalePeninsula_256_ft.jpg
gfx/env/DalePeninsula_256_ft.pcx
gfx/env/DalePeninsula_256_ft.tga
gfx/env/DalePeninsula_256_lf.bmp
gfx/env/DalePeninsula_256_lf.jpg
gfx/env/DalePeninsula_256_lf.pcx
gfx/env/DalePeninsula_256_lf.tga
gfx/env/DalePeninsula_256_rt.bmp
gfx/env/DalePeninsula_256_rt.jpg
gfx/env/DalePeninsula_256_rt.pcx
gfx/env/DalePeninsula_256_rt.tga
gfx/env/DalePeninsula_256_up.bmp
gfx/env/DalePeninsula_256_up.jpg
gfx/env/DalePeninsula_256_up.pcx
gfx/env/DalePeninsula_256_up.tga