halflife.wad
liquids.wad
spraypaint.wad
xeno.wad
cached.wad
decals.wad
fonts.wad
gfx.wad
2bases2.wad
sprites/e-tele1.spr
sprites/smokepuff.spr
maps/Sparrows_op_1.cfg
maps/Sparrows_op_1.res
maps/Sparrows_op_1_motd.txt