gfx/env/2desertbk.tga
gfx/env/2desertdn.tga
gfx/env/2desertft.tga
gfx/env/2desertlf.tga
gfx/env/2desertrt.tga
gfx/env/2desertup.tga
halflife.wad
liquids.wad
maps/the-climb.cfg
maps/the-climb_motd.txt
models/ball.mdl
sound/ambience/steamjet1.wav
sound/ambience/waterfall3.wav
sound/ambience/wind2.wav
sound/ambience/wren1.wav
sound/debris/beamstart14.wav
sound/tfc/ambience/goal_1.wav
sprites/d-tele1.spr
sprites/e-tele1.spr
sprites/xsmoke1.spr
tfc.wad
tfc2.wad
xeno.wad
