gfx/env/2desertbk.tga
gfx/env/2desertdn.tga
gfx/env/2desertft.tga
gfx/env/2desertlf.tga
gfx/env/2desertrt.tga
gfx/env/2desertup.tga
halflife.wad
liquids.wad
maps/the-climb3.cfg
maps/the-climb3_motd.txt
sound/ambience/steamburst1.wav
sound/ambience/steamjet1.wav
sound/ambience/waterfall3.wav
sound/ambience/wind1.wav
sound/ambience/wind2.wav
sound/debris/beamstart8.wav
sound/tfc/ambience/goal_1.wav
sound/weapons/dryfire1.wav
sprites/d-tele1.spr
sprites/e-tele1.spr
sprites/stmbal1.spr
sprites/xsmoke1.spr
tfc.wad
tfc2.wad
xeno.wad
