// Created with resguy v6 (November 2017)
// https://github.com/wootguy/resguy

gfx/env/hjhill_skybk.tga
gfx/env/hjhill_skydn.tga
gfx/env/hjhill_skyft.tga
gfx/env/hjhill_skylf.tga
gfx/env/hjhill_skyrt.tga
gfx/env/hjhill_skyup.tga
models/player/touhou_aya/touhou_aya.bmp
models/player/touhou_aya/touhou_aya.mdl
models/player/touhou_cirno/touhou_cirno.bmp
models/player/touhou_cirno/touhou_cirno.mdl
models/player/touhou_flandre/touhou_flandre.bmp
models/player/touhou_flandre/touhou_flandre.mdl
models/player/touhou_koakuma/touhou_koakuma.bmp
models/player/touhou_koakuma/touhou_koakuma.mdl
models/player/touhou_marisa/touhou_marisa.bmp
models/player/touhou_marisa/touhou_marisa.mdl
models/player/touhou_mokou/touhou_mokou.bmp
models/player/touhou_mokou/touhou_mokou.mdl
models/player/touhou_reimu/touhou_reimu.bmp
models/player/touhou_reimu/touhou_reimu.mdl
models/player/touhou_remilia/touhou_remilia.bmp
models/player/touhou_remilia/touhou_remilia.mdl
models/player/touhou_rumia/touhou_rumia.bmp
models/player/touhou_rumia/touhou_rumia.mdl
models/player/touhou_sakuya/touhou_sakuya.bmp
models/player/touhou_sakuya/touhou_sakuya.mdl
models/player/touhou_sanae/touhou_sanae.bmp
models/player/touhou_sanae/touhou_sanae.mdl
models/player/touhou_tenshi/touhou_tenshi.bmp
models/player/touhou_tenshi/touhou_tenshi.mdl
models/player/touhou_udongein/touhou_udongein.mdl
models/player/touhou_youmu/touhou_youmu.bmp
models/player/touhou_youmu/touhou_youmu.mdl
models/touhou_mapmdl/appel3.mdl
models/touhou_mapmdl/bush_g.mdl
models/touhou_mapmdl/flower_01.mdl
models/touhou_mapmdl/grass_3.mdl
models/touhou_mapmdl/leaf_03.mdl
models/touhou_mapmdl/rama.mdl
models/touhou_mapmdl/tree_01.mdl
sound/touhou_mapwav/battlebgm1.wav
sound/touhou_mapwav/battlebgm2.wav
sound/touhou_mapwav/battlebgm3.wav
sound/touhou_mapwav/bossbattle.wav
sound/touhou_mapwav/gamendbgm.wav
sound/touhou_mapwav/gamestart.wav
sound/touhou_mapwav/picksorce.wav
